apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../infra/longhorn
  - ../../../infra/metrics-server
  - ../../../infra/pod-report
  - ../../../infra/cloudflared
  - ../../../infra/tailscale
  - ../../../secrets/tailscale-auth.enc.yaml
