apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../infra/longhorn
  - ../../../infra/metrics-server
  - ../../../infra/pod-report
  - ../../../infra/cloudflared
  - ../../../infra/tailscale
  - ../../../infra/backups
  - ../../../secrets/tailscale-auth.enc.yaml
  - ../../../secrets/longhorn-b2-credentials.enc.yaml
  - ../../../secrets/restic-b2-photos.enc.yaml
