apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage
resources:
  - namespace.yaml
  - pvc.yaml
  - assets-pvc.yaml
  - rbac.yaml
  - configmap.yaml
  - assets-deployment.yaml
  - assets-service.yaml
  - deployment.yaml
  - service.yaml
