apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage
resources:
  - namespace.yaml
  - pvc.yaml
  - assets-pvc.yaml
  - rbac.yaml
  - assets-deployment.yaml
  - assets-service.yaml
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: homepage-app-config
    files:
      - config/settings.yaml
      - config/services.yaml
      - config/bookmarks.yaml
      - config/widgets.yaml
      - config/kubernetes.yaml
      - config/custom.css
  - name: homepage-public-icons
    files:
      - config/icons/wotlk.svg
      - config/icons/accountmgr.svg
      - config/icons/mariadb.svg

generatorOptions:
  disableNameSuffixHash: false
