apiVersion: apps/v1
kind: Deployment
metadata:
  name: wow-realmd
  namespace: wow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wow-realmd
  template:
    metadata:
      labels:
        app: wow-realmd
    spec:
      containers:
        - name: realmd
          image: ghcr.io/rovxbot/mangoszero:server-v22.04.105
          imagePullPolicy: Always
          env:
            - name: WOW_MODE
              value: realmd
            - name: DB_HOST
              value: wow-mariadb.wow.svc.cluster.local
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: wow-mariadb-auth
                  key: MARIADB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wow-mariadb-auth
                  key: MARIADB_PASSWORD
            - name: DB_REALM_DB
              value: realmd
            - name: REALM_PORT
              value: "3724"
          ports:
            - name: realm
              containerPort: 3724
              protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 1Gi
