apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../apps/prowlarr
  - ../../../../apps/radarr
  - ../../../../apps/sonarr
  - ../../../../apps/sabnzbd
  - ../../../../apps/jellyseerr
