apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../apps/shared
  - ../../../../apps/jellyfin
  - ../../../../apps/immich
  - ../../../../apps/ollama
  - ../../../../apps/vaultwarden
