apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dashboards/homelab-overview-dashboard.yaml
  - probes/blackbox-internal.yaml
  - probes/blackbox-external.yaml
  - servicemonitors/cloudflared-metrics.yaml
  - servicemonitors/longhorn-backend.yaml

